// src/data/seedProducts.js

const seedProducts = [
  {
    name: 'Mercedes-Benz C-Class Sedan',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    price: 48000.0,
    color: 'Polar White',
    mileage: 1500,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'A sophisticated blend of luxury and sportiness, the C-Class Sedan offers advanced technology and a refined driving experience.',
    image_url: 'https://placehold.co/600x400/E0E0E0/333333?text=C-Class+Sedan',
    featured: 1,
  },
  {
    name: 'Mercedes-Benz GLC SUV',
    brand: 'Mercedes-Benz',
    model: 'GLC',
    year: 2024,
    price: 55000.0,
    color: 'Obsidian Black',
    mileage: 500,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'The GLC SUV combines elegant design with robust performance, perfect for both city driving and adventurous escapes.',
    image_url: 'https://placehold.co/600x400/D0D0D0/444444?text=GLC+SUV',
    featured: 1,
  },
  {
    name: 'Mercedes-Benz E-Class Coupe',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2023,
    price: 68000.0,
    color: 'Selenite Grey',
    mileage: 2000,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'Experience exhilarating performance and breathtaking style with the E-Class Coupe, a true masterpiece of automotive design.',
    image_url: 'https://placehold.co/600x400/C0C0C0/555555?text=E-Class+Coupe',
    featured: 0,
  },
  {
    name: 'Mercedes-AMG GT 4-Door Coupe',
    brand: 'Mercedes-AMG',
    model: 'GT 4-Door Coupe',
    year: 2024,
    price: 105000.0,
    color: 'Designo Diamond White Bright',
    mileage: 100,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'Unleash pure power and dynamic handling with the AMG GT 4-Door Coupe, a high-performance vehicle designed for thrill-seekers.',
    image_url: 'https://placehold.co/600x400/B0B0B0/666666?text=AMG+GT+4-Door',
    featured: 1,
  },
  {
    name: 'Mercedes-Benz S-Class Sedan',
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    year: 2023,
    price: 115000.0,
    color: 'Nautical Blue Metallic',
    mileage: 800,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'The epitome of luxury, the S-Class Sedan offers unparalleled comfort, innovative features, and a commanding presence.',
    image_url: 'https://placehold.co/600x400/A0A0A0/777777?text=S-Class+Sedan',
    featured: 1,
  },
  {
    name: 'Mercedes-Benz EQE Sedan',
    brand: 'Mercedes-Benz',
    model: 'EQE',
    year: 2024,
    price: 75000.0,
    color: 'Graphite Grey Metallic',
    mileage: 50,
    transmission: 'Automatic',
    fuel_type: 'Electric',
    description:
      'Step into the future with the all-electric EQE Sedan, combining sustainable luxury with cutting-edge technology and impressive range.',
    image_url: 'https://placehold.co/600x400/909090/888888?text=EQE+Sedan',
    featured: 0,
  },
  {
    name: 'Mercedes-Benz G-Class SUV',
    brand: 'Mercedes-Benz',
    model: 'G-Class',
    year: 2023,
    price: 140000.0,
    color: 'Desert Sand',
    mileage: 1200,
    transmission: 'Automatic',
    fuel_type: 'Petrol',
    description:
      'An iconic off-roader, the G-Class SUV offers rugged capability paired with luxurious interiors and timeless design.',
    image_url: 'https://placehold.co/600x400/808080/999999?text=G-Class+SUV',
    featured: 1,
  },
];

module.exports = seedProducts;
